### ISSUE TITLE
flutter run出现VM snapshot must be valid. Check failed: vm. Must be able to initialize the VM.

### ISSUE THREAD

**Issue by OrdinaryPath** [nesger/FlutterNote#5]
电脑新搭建的环境，flutter create创建了一个demo，flutter run的时候出现了VM snapshot must be valid. Check failed: vm. Must be able to initialize the VM.这个问题，小白google了一天都无法解决！！大佬能给个解决思路吗？

**Comment by nesger** [comment]
@OrdinaryPath 
你好，如果你是在旧有 Andorid 项目引入 Flutter 之后，运行出现上面问题，可以执行下面命令试下
```
./gradlew clean;cd sub/my_flutter/;flutter packages get;flutter clean;cd -;cd sub/my_flutter/.android/;./gradlew clean;./gradlew assemble;cd -;./gradlew assemble
```
总结起来就是：
```
清理项目；进入flutter module；更新包信息和清理；返回当前目录；进入flutter module .android 项目目录；清理打包；返回当前目录；打包
```
当然上面的一些路径可能你需要进行对应修改。  
建议阅读我之前写过的一篇文章，我出现一样的问题就是在旧有项目引入 Flutter，并且通过上面的方式处理解决的。  
可以仔细阅读下面文章：  
https://mp.weixin.qq.com/s/OGbH3G3wHVTUt-0EJit8RA

**Comment by OrdinaryPath** [comment]
不！我是新搭建的环境，而且是新创的flutter项目，并且不是在旧Android项目引入Flutter项目，所偶一我没有flutter module文件

**Comment by nesger** [comment]
@OrdinaryPath 
有几个问题需要你确认下：  
1. 你的开发 IDE 是？Android Studio 吗？
2. 你是创建一个纯 Flutter 项目，然后命令行运行报错吗？
3. 你的运行设备是真机还是模拟器？

**Comment by OrdinaryPath** [comment]
1.我的开发工具是AS，但是我常见项目是命令创建的（系统是windows10）
2.我是纯Flutter项目，然后再powsershell输入flutter run它报错的
3.真机和模拟器我都试过，他们都报同样的错误（真机我试过三种安卓机：红米，华为，oppo）

**Comment by OrdinaryPath** [comment]
1.我的开发工具是AS，但是我创建项目是命令创建的（系统是windows10）
2.我是纯Flutter项目，然后再powsershell输入flutter run它报错的
3.真机和模拟器我都试过，他们都报同样的错误（真机我试过三种安卓机：红米，华为，oppo）

**Comment by nesger** [comment]
@OrdinaryPath 
你试下用 AS 直接创建看看，然后直接点击 run 运行，看看是否有问题？

**Comment by OrdinaryPath** [comment]
可以的话，能否留一下您的联系方式我加一下您！

**Comment by nesger** [comment]
@OrdinaryPath 你发下邮件到我邮箱 nesger.zhan@gmail.com，我邮箱回复你联系方式

**Comment by OrdinaryPath** [comment]
已经发送过去了！您查收一下！

**Comment by OrdinaryPath** [comment]
大佬，我这个问题还是没解决！
